
[functions.send-verification-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-verification-email/deno.json"
entrypoint = "./functions/send-verification-email/index.ts"

[functions.create-verified-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-verified-user/index.ts"
